name: Release CI

on:
  release:
    types:
      - published

env:
  MINECRAFT_VERSION: 1.20
  JAVA_VERSION: 17
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - name: Build
        run: ./gradlew build
      - name: Publish to Modrinth, CurseForge & GitHub
        uses: Kir-Antipov/mc-publish@v3.2
        with:
         modrinth-id: TVSdsuq1
         modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

         curseforge-id: 877375
         curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

         github-token: ${{ secrets.GITHUB_TOKEN }}

         name: "[${{env.MINECRAFT_VERSION }}] Capybara Mod v${{env.VERSION}}"
         version: "${{env.VERSION}}"
         version-type: release

         loaders: fabric
         game-versions: "${{env.MINECRAFT_VERSION}}"
         java: "${{env.JAVA_VERSION}}"

         version-resolver: latest
